# Generated by Django 5.0.3 on 2025-09-01 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes confidentielles'),
        ),
        migrations.AddField(
            model_name='employe',
            name='prenom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('Benevole', 'Bénévole')], default='CDI', max_length=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
