# Generated by Django 5.0.3 on 2025-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personnel', '0002_employe_nom_employe_notes_employe_prenom_and_more'),
        ('sites_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites_gestion.siteorphelinat', verbose_name="Sites d'affectation"),
        ),
    ]
