# Generated by Django 5.0.3 on 2025-08-30 14:14

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEnfant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
                ('motif_admission', models.TextField(blank=True, verbose_name="Motif d'admission")),
                ('histoire', models.TextField(blank=True, verbose_name="Histoire de l'enfant")),
                ('statut', models.CharField(choices=[('accueilli', 'Accueilli'), ('adopte', 'Adopté'), ('reunifie', 'Réunifié (famille)'), ('majeur', 'Majeur / Départ')], default='accueilli', max_length=15)),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Enfant',
                'verbose_name_plural': 'historical Enfants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NoteEvolutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(verbose_name='Note sur le comportement/développement')),
            ],
            options={
                'verbose_name': 'Note Évolutive',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField()),
                ('type_consultation', models.CharField(help_text='Ex: Généraliste, Vaccin, Dentiste...', max_length=100)),
                ('medecin', models.CharField(blank=True, max_length=100)),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes supplémentaires')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suivi Médical',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(help_text='Format: 2024-2025', max_length=9)),
                ('ecole', models.CharField(max_length=150, verbose_name='Établissement scolaire')),
                ('classe', models.CharField(max_length=50)),
                ('resultats', models.TextField(blank=True, verbose_name='Résultats et appréciations')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suivi Scolaire',
                'ordering': ['-annee_scolaire'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_enfants/')),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
                ('motif_admission', models.TextField(blank=True, verbose_name="Motif d'admission")),
                ('histoire', models.TextField(blank=True, verbose_name="Histoire de l'enfant")),
                ('statut', models.CharField(choices=[('accueilli', 'Accueilli'), ('adopte', 'Adopté'), ('reunifie', 'Réunifié (famille)'), ('majeur', 'Majeur / Départ')], default='accueilli', max_length=15)),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_gestion.siteorphelinat', verbose_name="Site d'accueil")),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('acte_naissance', 'Acte de naissance'), ('jugement', "Jugement d'admission"), ('carnet_sante', 'Carnet de santé'), ('bulletin_scolaire', 'Bulletin scolaire'), ('autre', 'Autre')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(upload_to='documents_enfants/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enfants_gestion.enfant')),
            ],
        ),
    ]
