# Generated by Django 5.0.3 on 2025-08-30 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfants_gestion', '0001_initial'),
        ('sites_gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalenfant',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalenfant',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites_gestion.siteorphelinat', verbose_name="Site d'accueil"),
        ),
        migrations.AddField(
            model_name='noteevolutive',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteevolutive',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_evolutives', to='enfants_gestion.enfant'),
        ),
        migrations.AddField(
            model_name='suivimedical',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_medicaux', to='enfants_gestion.enfant'),
        ),
        migrations.AddField(
            model_name='suiviscolaire',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_scolaires', to='enfants_gestion.enfant'),
        ),
        migrations.AlterUniqueTogether(
            name='suiviscolaire',
            unique_together={('enfant', 'annee_scolaire')},
        ),
    ]
