# Generated by Django 5.0.3 on 2025-09-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_initial_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_comptable_central',
            field=models.BooleanField(default=False, help_text="Cochez cette case si l'utilisateur doit avoir accès aux finances de tous les sites.", verbose_name='Comptable Central'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('directeur', 'Directeur'), ('soignant', 'Soignant'), ('comptable', 'Comptable'), ('benevole', 'Bénévole')], max_length=20),
        ),
    ]
