# Generated by Django 5.0.3 on 2025-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_align_roles_and_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Directeur', 'Directeur'), ('Comptable', 'Comptable'), ('Soignant', 'Soignant'), ('Gestionnaire', 'Gestionnaire'), ('Bénévole', 'Bénévole'), ('Secrétaire', 'Secrétaire'), ('RH', 'RH')], max_length=20),
        ),
    ]
