# Generated by Django 5.0.3 on 2025-09-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_gestion', '0001_initial'),
        ('utilisateurs', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='site',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Les sites auxquels cet utilisateur a accès. Laisser vide pour donner accès à tous les sites (pour les rôles globaux).', to='sites_gestion.siteorphelinat', verbose_name='Sites autorisés'),
        ),
    ]
