# Generated by Django 5.0.3 on 2025-09-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfants_gestion', '0002_initial'),
        ('sites_gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_gestion.siteorphelinat')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(help_text='Ex: Loyer, Nourriture, Salaires...', max_length=100)),
                ('date_depense', models.DateField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_financiere.comptefinancier')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_gestion.siteorphelinat')),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donateur', models.CharField(blank=True, default='Anonyme', max_length=200)),
                ('date_don', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_financiere.comptefinancier')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites_gestion.siteorphelinat')),
            ],
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrain_nom', models.CharField(max_length=200, verbose_name='Nom du parrain/marraine')),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_debut', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfants_gestion.enfant')),
            ],
        ),
    ]
