# Generated by Django 5.0.3 on 2025-09-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfants_gestion', '0002_initial'),
        ('gestion_financiere', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='don',
            name='site',
        ),
        migrations.AddField(
            model_name='parrainage',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parrainage',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrainages', to='enfants_gestion.enfant'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('categorie', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transaction', models.DateField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gestion_financiere.comptefinancier')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parrainage_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='gestion_financiere.parrainage')),
            ],
            options={
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.DeleteModel(
            name='Depense',
        ),
        migrations.DeleteModel(
            name='Don',
        ),
    ]
