# Generated by Django 5.0.3 on 2025-09-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiere', '0002_remove_don_compte_remove_don_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrainage',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Laissez vide si le parrainage est toujours actif.', null=True),
        ),
    ]
